pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                 script {
                    def deliverScript = "${WORKSPACE}/jenkins/deliver.sh"
                    if (fileExists(deliverScript)) {
                        // Ensure the script has execute permissions
                        sh "chmod +x ${deliverScript}"
                        // Execute the script
                        sh deliverScript
                    } else {
                        error "Script not found: ${deliverScript}"
                    }
                }
            }
        }
    }
}
