pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                 dir("jenkins"){
                     sh "pwd"
                }
            }
        }
        stage('Finish'){
            steps {
                echo 'Pipeline Success with auto trigger!'
            }
        }
    }
}
